version: '3.9'
services:
  tweetero_app:
    container_name: tweetero_app
    build: .
    command: npm run dev
    ports:
     - 5000:4002
    depends_on:
      - tweetero_db
    volumes:
      - .:/usr/src/app
  tweetero_db:
    image: postgres:14
    container_name: tweetero_db
    hostname: ${POSTGRES_HOST}
    ports:
      - 2345:${POSTGRES_PORT}
    restart: always
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
